# Generated by Django 5.1.2 on 2024-10-31 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Возрастное ограничение')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='слаг')),
            ],
            options={
                'verbose_name': 'Ограничение',
                'verbose_name_plural': 'Ограничения',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название жанра')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='слаг')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studios_name', models.CharField(max_length=70, verbose_name='Название студии')),
                ('image', models.ImageField(blank=True, null=True, upload_to='studios_image/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Студия',
                'verbose_name_plural': 'Студии',
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('original_name', models.CharField(max_length=150, verbose_name='Оригинальное название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cover', models.ImageField(upload_to='anime_cover/', verbose_name='Обложка')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Рейтинг')),
                ('year_of_manufacture', models.DateField(verbose_name='Год выхода')),
                ('author', models.CharField(blank=True, max_length=70, null=True, verbose_name='Автор')),
                ('duration', models.CharField(blank=True, max_length=50, null=True, verbose_name='Длительность серии')),
                ('total_episodes', models.IntegerField(blank=True, null=True, verbose_name='Всего серий')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('anime_type', models.CharField(choices=[('series', 'Сериал'), ('movie', 'Полнометражный')], max_length=10, verbose_name='Тип аниме')),
                ('anime_file', models.FileField(blank=True, null=True, upload_to='movies/', verbose_name='Аниме файл')),
                ('age_limit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_limit', to='anime.age')),
            ],
            options={
                'verbose_name': 'Анимация',
                'verbose_name_plural': 'Анимации',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField(verbose_name='Номер серии')),
                ('title', models.CharField(max_length=150, verbose_name='Название серии')),
                ('file', models.FileField(upload_to='episodes/', verbose_name='Файл серии')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='anime.anime')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='series_files',
            field=models.ManyToManyField(blank=True, related_name='anime_series', to='anime.episode'),
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.ManyToManyField(related_name='Жанр', to='anime.genre'),
        ),
        migrations.AddField(
            model_name='anime',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Статус', to='anime.status'),
        ),
        migrations.AddField(
            model_name='anime',
            name='studios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Студия', to='anime.studio'),
        ),
    ]
