# Generated by Django 5.1.2 on 2024-11-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_season_episode_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='year_of_manufacture',
            field=models.DateField(blank=True, null=True, verbose_name='Год выхода'),
        ),
    ]
