# Generated by Django 5.1.2 on 2024-11-01 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_anime_banner_alter_anime_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='duration_film',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Длительность фильма'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Статус', to='anime.status'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='year_of_manufacture',
            field=models.CharField(blank=True, null=True, verbose_name='Год выхода'),
        ),
    ]
