# Generated by Django 5.1.2 on 2024-11-03 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anime.episode'),
        ),
    ]
