# Generated by Django 5.1.2 on 2024-11-03 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_comment_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='anime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anime.anime'),
        ),
    ]
