# Generated by Django 5.1.2 on 2024-11-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_comment_anime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='anime',
        ),
    ]
