# Generated by Django 5.1.2 on 2024-11-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_remove_comment_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
