# Generated by Django 5.1.2 on 2024-11-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_favorites'),
        ('anime', '0010_studio_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_myself',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorites_genre',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_genre', to='anime.genre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorites_anime', to='anime.anime'),
        ),
    ]
